add wave -position end  sim:/test_sisa/SoC/CLOCK_50
add wave -position end  sim:/test_sisa/SoC/SRAM_ADDR
add wave -position end  sim:/test_sisa/SoC/SRAM_DQ
add wave -position end  sim:/test_sisa/SoC/SRAM_UB_N
add wave -position end  sim:/test_sisa/SoC/SRAM_LB_N
add wave -position end  sim:/test_sisa/SoC/SRAM_CE_N
add wave -position end  sim:/test_sisa/SoC/SRAM_OE_N
add wave -position end  sim:/test_sisa/SoC/SRAM_WE_N
add wave -position end  sim:/test_sisa/SoC/SW
add wave -position end  sim:/test_sisa/SoC/s_word_byte
add wave -position end  sim:/test_sisa/SoC/s_wr_m
add wave -position end  sim:/test_sisa/SoC/s_addr_m
add wave -position end  sim:/test_sisa/SoC/s_data_wr
add wave -position end  sim:/test_sisa/SoC/s_rd_data
add wave -position end  sim:/test_sisa/SoC/s_reg_divisor
add wave -position end  sim:/test_sisa/SoC/memctrl0/CLOCK_50
add wave -position end  sim:/test_sisa/SoC/memctrl0/addr
add wave -position end  sim:/test_sisa/SoC/memctrl0/wr_data
add wave -position end  sim:/test_sisa/SoC/memctrl0/rd_data
add wave -position end  sim:/test_sisa/SoC/memctrl0/we
add wave -position end  sim:/test_sisa/SoC/memctrl0/byte_m
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_ADDR
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_DQ
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_UB_N
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_LB_N
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_CE_N
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_OE_N
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_WE_N
add wave -position end  sim:/test_sisa/SoC/memctrl0/s_sram_data_readed
add wave -position end  sim:/test_sisa/SoC/memctrl0/s_sram_wr
