add wave -divider SoC
add wave -position end  sim:/test_sisa/SoC/CLOCK_50
add wave -position end  sim:/test_sisa/SoC/SRAM_ADDR
add wave -position end  sim:/test_sisa/SoC/SRAM_DQ
add wave -position end  sim:/test_sisa/SoC/SRAM_UB_N
add wave -position end  sim:/test_sisa/SoC/SRAM_LB_N
add wave -position end  sim:/test_sisa/SoC/SRAM_CE_N
add wave -position end  sim:/test_sisa/SoC/SRAM_OE_N
add wave -position end  sim:/test_sisa/SoC/SRAM_WE_N
add wave -position end  sim:/test_sisa/SoC/SW
add wave -position end  sim:/test_sisa/SoC/s_word_byte
add wave -position end  sim:/test_sisa/SoC/s_wr_m
add wave -position end  sim:/test_sisa/SoC/s_addr_m
add wave -position end  sim:/test_sisa/SoC/s_data_wr
add wave -position end  sim:/test_sisa/SoC/s_rd_data
add wave -position end  sim:/test_sisa/SoC/s_reg_divisor
add wave -divider MemoryController
add wave -position end  sim:/test_sisa/SoC/memctrl0/CLOCK_50
add wave -position end  sim:/test_sisa/SoC/memctrl0/addr
add wave -position end  sim:/test_sisa/SoC/memctrl0/wr_data
add wave -position end  sim:/test_sisa/SoC/memctrl0/rd_data
add wave -position end  sim:/test_sisa/SoC/memctrl0/we
add wave -position end  sim:/test_sisa/SoC/memctrl0/byte_m
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_ADDR
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_DQ
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_UB_N
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_LB_N
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_CE_N
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_OE_N
add wave -position end  sim:/test_sisa/SoC/memctrl0/SRAM_WE_N
add wave -position end  sim:/test_sisa/SoC/memctrl0/s_sram_data_readed
add wave -position end  sim:/test_sisa/SoC/memctrl0/s_sram_wr
add wave -divider Memory_Values
add wave -position end  sim:/test_sisa/mem0/mem_array(60)
add wave -position end  sim:/test_sisa/mem0/mem_array(59)
add wave -position end  sim:/test_sisa/mem0/mem_array(58)
add wave -position end  sim:/test_sisa/mem0/mem_array(57)
add wave -position end  sim:/test_sisa/mem0/mem_array(56)
add wave -position end  sim:/test_sisa/mem0/mem_array(55)
add wave -position end  sim:/test_sisa/mem0/mem_array(54)
add wave -position end  sim:/test_sisa/mem0/mem_array(53)
add wave -position end  sim:/test_sisa/mem0/mem_array(52)
add wave -position end  sim:/test_sisa/mem0/mem_array(51)
add wave -position end  sim:/test_sisa/mem0/mem_array(50)
add wave -position end  sim:/test_sisa/mem0/mem_array(49)
add wave -position end  sim:/test_sisa/mem0/mem_array(48)
add wave -position end  sim:/test_sisa/mem0/mem_array(47)
add wave -position end  sim:/test_sisa/mem0/mem_array(46)
add wave -position end  sim:/test_sisa/mem0/mem_array(45)
add wave -position end  sim:/test_sisa/mem0/mem_array(44)
add wave -position end  sim:/test_sisa/mem0/mem_array(43)
add wave -position end  sim:/test_sisa/mem0/mem_array(42)
add wave -position end  sim:/test_sisa/mem0/mem_array(41)
add wave -position end  sim:/test_sisa/mem0/mem_array(40)
add wave -position end  sim:/test_sisa/mem0/mem_array(39)
add wave -position end  sim:/test_sisa/mem0/mem_array(38)
add wave -position end  sim:/test_sisa/mem0/mem_array(37)
add wave -position end  sim:/test_sisa/mem0/mem_array(36)
add wave -position end  sim:/test_sisa/mem0/mem_array(35)
add wave -position end  sim:/test_sisa/mem0/mem_array(34)
add wave -position end  sim:/test_sisa/mem0/mem_array(33)
add wave -position end  sim:/test_sisa/mem0/mem_array(32)
add wave -position end  sim:/test_sisa/mem0/mem_array(31)
add wave -position end  sim:/test_sisa/mem0/mem_array(30)
add wave -position end  sim:/test_sisa/mem0/mem_array(29)
add wave -position end  sim:/test_sisa/mem0/mem_array(28)
add wave -position end  sim:/test_sisa/mem0/mem_array(27)
add wave -position end  sim:/test_sisa/mem0/mem_array(26)
add wave -position end  sim:/test_sisa/mem0/mem_array(25)
add wave -position end  sim:/test_sisa/mem0/mem_array(24)
add wave -position end  sim:/test_sisa/mem0/mem_array(23)
add wave -position end  sim:/test_sisa/mem0/mem_array(22)
add wave -position end  sim:/test_sisa/mem0/mem_array(21)
add wave -position end  sim:/test_sisa/mem0/mem_array(20)
add wave -position end  sim:/test_sisa/mem0/mem_array(19)
add wave -position end  sim:/test_sisa/mem0/mem_array(18)
add wave -position end  sim:/test_sisa/mem0/mem_array(17)
add wave -position end  sim:/test_sisa/mem0/mem_array(16)
add wave -position end  sim:/test_sisa/mem0/mem_array(15)
add wave -position end  sim:/test_sisa/mem0/mem_array(14)
add wave -position end  sim:/test_sisa/mem0/mem_array(13)
add wave -position end  sim:/test_sisa/mem0/mem_array(12)
add wave -position end  sim:/test_sisa/mem0/mem_array(11)
add wave -position end  sim:/test_sisa/mem0/mem_array(10)
add wave -position end  sim:/test_sisa/mem0/mem_array(9)
add wave -position end  sim:/test_sisa/mem0/mem_array(8)
add wave -position end  sim:/test_sisa/mem0/mem_array(7)
add wave -position end  sim:/test_sisa/mem0/mem_array(6)
add wave -position end  sim:/test_sisa/mem0/mem_array(5)
add wave -position end  sim:/test_sisa/mem0/mem_array(4)
add wave -position end  sim:/test_sisa/mem0/mem_array(3)
add wave -position end  sim:/test_sisa/mem0/mem_array(2)
add wave -position end  sim:/test_sisa/mem0/mem_array(1)
add wave -position end  sim:/test_sisa/mem0/mem_array(0)
