name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List Files
      using: docker
      run: |
        cd ${{ github.workspace }}
        ls -la
        make ETAPA=6
