name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-compilation:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/SW1073/PEC-SISA
      - run: cd PEC-SISA/
      - run: make ETAPA=7.1
